disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - force_unwrapping
  - sorted_imports

line_length:
  warning: 120
  error: 180

identifier_name:
  min_length: 2

excluded:
  - Pods
  - Carthage
  - DerivedData
