default_platform(:ios)

platform :ios do

  desc "Build IPA"

  lane :beta do
  build_app(
    project: "TaskFlow.xcodeproj",
    scheme: "TaskFlow",
    configuration: "Release",
    export_method: "development",
    export_options: {
      provisioningProfiles: {
        "com.app.mpmoney" => "MPMoneyDevelopment"
      }
    }
  )
end

end