default_platform(:ios)

platform :ios do

  desc "Build project for CI"

  lane :ci do
    build_app(
      project: "TaskFlow.xcodeproj",
      scheme: "TaskFlow",
      configuration: "Debug",
      sdk: "iphonesimulator",
      skip_codesigning: true,
      skip_archive: true
    )
  end

end