require 'base64'

default_platform(:ios)

platform :ios do

  desc "Upload build to TestFlight"

  lane :beta do

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: Base64.decode64(ENV["APP_STORE_CONNECT_API_KEY"])
    )

    build_app(
      project: "TaskFlow.xcodeproj",
      scheme: "TaskFlow",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.app.jokerztest" => "Jokerz_Distribution"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )

  end

end