name: iOS CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint

      - name: Resolve Packages
        run: |
          xcodebuild \
            -resolvePackageDependencies \
            -project TaskFlow.xcodeproj

      - name: Install Gems
        run: bundle install

      - name: Fastlane Build
        run: bundle exec fastlane ci
